name: Automated Tests and Dependency Caching

on: [push]

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Cache Dependencies
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Packages
        run: yarn

      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: yarn dev
          wait-on: http://localhost:3000
